'use client';

import { useEffect, useRef, useState } from 'react';
import { BellIcon } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { NotificationDropdown } from '@/features/notifications/components/notification-dropdown';
import { useUnreadCount } from '@/features/notifications/hooks';

/**
 * The application's single notification source.
 *
 * Phase 6.3 consolidated the two competing bells: the dashboard used to render
 * its own copy next to a shell-level placeholder, which meant two truths for
 * unread state. The shell now owns exactly one bell.
 *
 * Phase 6.9 moved the badge onto its own endpoint (`/notifications/unread-count`)
 * rather than reading `unread_count` out of the full list: the bell only needs
 * a number, and it now polls every 60s and on window focus, so a deadline
 * notification generated by the nightly sweep actually surfaces. The number
 * still comes from the API — there is no UI-only notification state.
 */
export function NotificationBell() {
  const [open, setOpen] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);
  const { data: unread, isPending } = useUnreadCount();

  const count = unread ?? 0;

  useEffect(() => {
    if (!open) {
      return;
    }

    const handlePointerDown = (event: PointerEvent) => {
      if (
        containerRef.current &&
        !containerRef.current.contains(event.target as Node)
      ) {
        setOpen(false);
      }
    };

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setOpen(false);
      }
    };

    document.addEventListener('pointerdown', handlePointerDown);
    document.addEventListener('keydown', handleKeyDown);

    return () => {
      document.removeEventListener('pointerdown', handlePointerDown);
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [open]);

  return (
    <div ref={containerRef} className="relative">
      <Button
        variant="outline"
        size="icon"
        aria-label={
          count > 0 ? `Notifications (${count} unread)` : 'Notifications'
        }
        aria-expanded={open}
        aria-haspopup="dialog"
        onClick={() => setOpen((value) => !value)}
        className="relative"
      >
        <BellIcon />
        {!isPending && count > 0 && (
          <span
            className="absolute -right-1.5 -top-1.5 flex h-4 min-w-4 items-center justify-center rounded-full bg-destructive px-1 text-[10px] font-semibold tabular-nums text-destructive-foreground"
            aria-hidden="true"
          >
            {count > 9 ? '9+' : count}
          </span>
        )}
      </Button>

      {open && <NotificationDropdown onClose={() => setOpen(false)} />}
    </div>
  );
}

